### ISSUE TITLE
-q and -quality param ignored

### ISSUE THREAD

**Issue by OlliePugh** [meinside/rpi-mjpg-streamer#3]
Is it possible to set the quality of the stream I found this list of available commands for mjpeg-streamer (granted on an octoprint forum)
https://community.octoprint.org/t/available-mjpg-streamer-configuration-options/1106

Which states that the quality can be set, but if I add `-quality 1`, making the entire string:

`PLUGIN_IN="$MJPG_STREAMER_PLUGINS_DIR/input_uvc.so -d $DEVICE_IN -quality 0 -r $RESOLUTION -f $FPS -l $LED -hf true -vf true"`

and then restart the application, I get exactly the same quality stream!

Is quality a supported param?

**Comment by meinside** [comment]
Hi, I'm not the author of mjpg-streamer, but I see the flag [here](https://github.com/jacksonliam/mjpg-streamer/blob/85f89a8c321e799fabb1693c5d133f3fb48ee748/mjpg-streamer-experimental/plugins/input_uvc/input_uvc.c#L536).

The flag seems to be in range from 1 to 100.
